apiVersion: batch/v1
kind: Job

metadata:
  name: train-job-0

spec:
  backoffLimit: 0
  template:
    spec:
      restartPolicy: Never
      containers:

        - name: C0
          image: gitlab-registry.nrp-nautilus.io/martinezci/cuda11.7base-ubuntu20.04:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 8Gi
              cpu: 4
              nvidia.com/gpu: 1
            requests:
              memory: 8Gi
              cpu: 4
              nvidia.com/gpu: 1
          env:
            - name: CONTAINER_ID
              value: 0
            - name: JOB_ID
              value: 0
          command: ["python3","test_script.py"]

        - name: C1
          image: gitlab-registry.nrp-nautilus.io/martinezci/cuda11.7base-ubuntu20.04:latest        
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 8Gi
              cpu: 4
              nvidia.com/gpu: 1
            requests:
              memory: 8Gi
              cpu: 4
              nvidia.com/gpu: 1
          env:
            - name: CONTAINER_ID
              value: 1
            - name: JOB_ID
              value: 0  
          command: ["python3","test_script.py"]

        - name: C2
          image: gitlab-registry.nrp-nautilus.io/martinezci/cuda11.7base-ubuntu20.04:latest        
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 8Gi
              cpu: 4
              nvidia.com/gpu: 1
            requests:
              memory: 8Gi
              cpu: 4
              nvidia.com/gpu: 1
          env:
            - name: CONTAINER_ID
              value: 2
            - name: JOB_ID
              value: 0      
          command: ["python3","test_script.py"]

        - name: C3
          image: gitlab-registry.nrp-nautilus.io/martinezci/cuda11.7base-ubuntu20.04:latest        
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              memory: 8Gi
              cpu: 4
              nvidia.com/gpu: 1
            requests:
              memory: 8Gi
              cpu: 4
              nvidia.com/gpu: 1
          env:
            - name: CONTAINER_ID
              value: 3
            - name:JOB_ID
              value: 0
          command: ["python3","test_script.py"]

      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nvidia.com/gpu.product
                    operator: In
                    values:
                      - NVIDIA-GeForce-RTX-3090
