apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: <the-actual-pvc-name>
  namespace: <your-namespace>
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
